name: batch-inference
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pyspark
  - openjdk
  - pip
  - pip:
      - ipykernel
      - mlflow
      - boto3==1.19.7
      - click==8.0.3
      - databricks-cli==0.16.2
      - ray[tune]==1.9.2
      - optuna==2.10.0