name: winepred-data-features
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - cloudpickle
  - pip:
    - git+git://github.com/mlflow/mlflow
    - pandas-profiling
    - great-expectations

name: winepred-training
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - git+git://github.com/mlflow/mlflow
    - sklearn
    - pandas_datareader
    - great-expectations==0.13.15
    - pandas-profiling
    - xgboost